# 프로덕션 환경 설정 (실제 서비스 운영)
server:
  port: ${PORT:8080}  # 클라우드 서비스에서 자동으로 포트 할당
  servlet:
    context-path: /api
  # 프로덕션 최적화
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 8192

spring:
  # 프로덕션 데이터베이스 설정 (환경변수로 관리)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DATABASE_URL:jdbc:mysql://prod-db-server:3306/nallijaku_prod_db?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${PROD_DATABASE_USERNAME:nallijaku_prod_user}
    password: ${PROD_DATABASE_PASSWORD}  # 반드시 환경변수로 설정
    
    # 커넥션 풀 최적화
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
    
  jpa:
    hibernate:
      ddl-auto: validate  # 프로덕션에서는 validate만 사용
    show-sql: false       # 프로덕션에서는 SQL 로그 비활성화
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# JWT 설정 (보안 강화)
jwt:
  secret: ${JWT_SECRET}  # 반드시 환경변수로 설정 (최소 32자)

# 로깅 설정 (프로덕션용)
logging:
  level:
    com.nallijaku.backend: INFO
    org.springframework.security: WARN
    org.hibernatL: WARN
    org.springframework.web: WARN
    root: INFO
  # 로그 파일 설정
  file:
    name: /var/log/nallijaku/application.log
    max-size: 100MB
    max-history: 30
    
# CORS 설정 (프로덕션 도메인만)
cors:
  allowed-origins: 
    - https://nallijaku.com
    - https://www.nallijaku.com
    - https://api.nallijaku.com
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# 파일 저장 경로 (프로덕션)
file:
  upload-dir: ${FILE_UPLOAD_DIR:/app/uploads/prod}

# 프로덕션 보안 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: never
  security:
    enabled: true

# 보안 강화 설정
server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: never
  tomcat:
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
      
# 추가 보안 헤더
security:
  headers:
    frame-options: DENY
    content-type-options: nosniff
    xss-protection: "1; mode=block"
    hsts: "max-age=31536000; includeSubDomains"
