# 로컬 개발 환경 설정 (개발자 개인 PC)
server:
  port: 9090
  servlet:
    context-path: /api

spring:
  # 로컬 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nallijaku_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: nallijaku_user
    password: password123
    
  jpa:
    hibernate:
      ddl-auto: update   # 로컬에서는 자유롭게 스키마 변경
    show-sql: true       # SQL 로그 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# JWT 설정 (로컬용 - 보안 낮음)
jwt:
  secret: nallijaku-local-development-secret-key-2024

# 로깅 설정 (디버그 모드)
logging:
  level:
    com.nallijaku.backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    root: INFO
    
# CORS 설정 (로컬 개발용)
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:3001
    - http://127.0.0.1:3000
    - http://127.0.0.1:3001
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# 파일 저장 경로 (로컬)
file:
  upload-dir: ./uploads/local
