# 날리자쿠 드론 교육 플랫폼 백엔드 - 공통 설정
spring:
  application:
    name: nallijaku-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
  # 자동 설정 제외 (Spring Security만 비활성화)
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  
  # 정적 리소스 설정
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
        
  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  # 이메일 설정 (환경별로 오버라이드)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:your-email@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT 설정 (환경별로 오버라이드)
jwt:
  expiration: 86400000 # 24시간 (밀리초)
  refresh-expiration: 604800000 # 7일 (밀리초)

# 파일 저장 경로 (환경별로 오버라이드)
file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}
